### ISSUE TITLE
Missing package in conda.yml

### ISSUE THREAD

**Issue by zlin7** [futianfan/clinical-trial-outcome-prediction#1]
When I run src/learn_phaseI.py

 File "/home/user/reproduce/clinical-trial-outcome-prediction/src/utils.py", line 12, in plot_hist
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'

**Comment by zlin7** [comment]
I tried installing but got the following error. I guess what you have is not seaborn=0.7.1 which is what conda installed by default. 

Traceback (most recent call last):
  File "src/learn_phaseI.py", line 83, in <module>
    model.learn(train_loader, valid_loader, test_loader)
  File "/home/user/reproduce/clinical-trial-outcome-prediction/src/model.py", line 191, in learn
    valid_loss = self.test(valid_loader, return_loss=True)
  File "/home/user/reproduce/clinical-trial-outcome-prediction/src/model.py", line 172, in test
    plot_hist(prefix_name, predict_all, label_all)
  File "/home/user/reproduce/clinical-trial-outcome-prediction/src/utils.py", line 17, in plot_hist
    sns.distplot(positive_prediction, hist=True,  kde=False, bins=50, color = 'blue', label = 'positive')
  File "/home/user/miniconda3/envs/predict_drug_clinical_trial/lib/python3.6/site-packages/seaborn/distributions.py", line 215, in distplot
    color=hist_color, **hist_kws)
  File "/home/user/miniconda3/envs/predict_drug_clinical_trial/lib/python3.6/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/user/miniconda3/envs/predict_drug_clinical_trial/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6819, in hist
    p.update(kwargs)
  File "/home/user/miniconda3/envs/predict_drug_clinical_trial/lib/python3.6/site-packages/matplotlib/artist.py", line 1006, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/home/user/miniconda3/envs/predict_drug_clinical_trial/lib/python3.6/site-packages/matplotlib/artist.py", line 1006, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/home/user/miniconda3/envs/predict_drug_clinical_trial/lib/python3.6/site-packages/matplotlib/artist.py", line 1002, in _update_property
    .format(type(self).__name__, k))
AttributeError: 'Rectangle' object has no property 'normed'

**Comment by futianfan** [comment]
Thanks. the seaborn version I use is 0.11.0.
